#inherit_from: .rubocop_todo.yml
require:
  - rubocop/cop/internal_affairs
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 2.4
  Exclude:
    - 'vendor/**/*'
    - 'spec/fixtures/**/*'
    - 'tmp/**/*'
    - 'db/schema.rb'
    - 'db/migrate/*'

Documentation:
  Enabled: false

Metrics/LineLength:
  Max: 120
  Exclude:
  - 'config/initializers/**/*'

Metrics/BlockLength:
  CountComments: false
  Max: 20

Metrics/MethodLength:
  CountComments: false
  Max: 20

Metrics/ModuleLength:
  CountComments: false
  Max: 150
